# Easy-MCP Docker Compose Configuration
# Version: v2.4.0 – Streamlined Professional Architecture
# Updated: 2025-06-29T22:16:41+08:00

volumes:
  mcp-filesystem-data:
    driver: local
  mcp-memory-data:
    driver: local
  mcp-logs:
    driver: local

secrets:
  mcp_secret_key:
    file: ./secrets/mcp_secret.txt
  filesystem_access_key:
    file: ./secrets/filesystem_key.txt

services:
  # ======= MCP Filesystem Service =======
  mcp-filesystem:
    build:
      context: ./mcp-services
      dockerfile: filesystem.Dockerfile
    container_name: mcp-filesystem-enhanced
    restart: unless-stopped
    volumes:
      - ./view:/app/projects:rw
    environment:
      - NODE_ENV=production
      - MCP_SERVICE_NAME=filesystem
      - MCP_LOG_LEVEL=info
      - MCP_ENABLE_WRITE=true
      - MCP_ENABLE_DELETE=true
      - MCP_ENABLE_CREATE=true
    stdin_open: true
    tty: true
    ports:
      - "8082:8082"
    labels:
      - "mcp.service=filesystem"
      - "mcp.type=core"
      - "mcp.version=2.4.0"
      - "mcp.permissions=read,write,create,delete"

  # ======= MCP Puppeteer Service =======
  mcp-puppeteer:
    build:
      context: ./mcp-services
      dockerfile: puppeteer.Dockerfile
    container_name: mcp-puppeteer-enhanced
    restart: unless-stopped
    privileged: true
    shm_size: "2gb"
    environment:
      - NODE_ENV=production
      - MCP_SERVICE_NAME=puppeteer
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false
    stdin_open: true
    tty: true
    ports:
      - "8084:8084"
    labels:
      - "mcp.service=puppeteer"
      - "mcp.type=utility"
      - "mcp.version=2.4.0"

  # ======= MCP Memory Service =======
  mcp-memory:
    build:
      context: ./mcp-services
      dockerfile: memory.Dockerfile
    container_name: mcp-memory-enhanced
    restart: unless-stopped
    volumes:
      - mcp-memory-data:/app/data:rw
    environment:
      - NODE_ENV=production
      - MCP_SERVICE_NAME=memory
      - MEMORY_FILE_PATH=/app/data/memory.json
      - MCP_LOG_LEVEL=info
    stdin_open: true
    tty: true
    ports:
      - "8085:8085"
    labels:
      - "mcp.service=memory"
      - "mcp.type=storage"
      - "mcp.version=2.4.0"
      - "mcp.features=knowledge-graph,persistence"

  # ======= MCP Everything Service =======
  mcp-everything:
    build:
      context: ./mcp-services
      dockerfile: everything.Dockerfile
    container_name: mcp-everything-enhanced
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MCP_SERVICE_NAME=everything
      - MCP_FEATURE_FLAGS=echo,add,longRunning,sampling
      - MCP_LOG_LEVEL=warn
      - MCP_ENABLE_METRICS=false
      - MCP_DEMO_MODE=false
      - MCP_NOTIFICATION_INTERVAL=300000
    stdin_open: true
    tty: true
    ports:
      - "8086:8086"
    labels:
      - "mcp.service=everything"
      - "mcp.type=utility"
      - "mcp.version=2.4.0"
